#ifndef NON_GRAVITAR_GAME_HPP
#define NON_GRAVITAR_GAME_HPP

#define NG_GAME_BASE_ENEMY_DENSITY 0.0002
#define NG_GAME_BASE_CRATE_DENSITY 0.00005


#define NG_GAME_PLANETOID_NUMBER        3
#define NG_GAME_PLANETOID_MIN_SIZE      100
#define NG_GAME_PLANETOID_MAX_SIZE      500

#endif //NON_GRAVITAR_GAME_HPP
